name: Colorblind Snapshot Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-colorblind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run colorblind snapshot analyzer
        uses: NotTheRealWallyx/colorblind-snapshot-analyzer@1.0.0
        with:
          inputDir: public
