name: Colorblind Snapshot Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test-colorblind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run colorblind snapshot analyzer
        uses: NotTheRealWallyx/colorblind-snapshot-analyzer@18-feature-swap-to-use-pdm-instead-of-requirementstxt
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
