name: Colorblind Snapshot Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test-colorblind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run colorblind snapshot analyzer
        uses: NotTheRealWallyx/LinkSentinel@1.0.0
        with:
          path: './docs'
